### PR TITLE
Fix build and add Python3 support

### PR DESCRIPTION
**Pull request by jamesobutler**
This attempts to fix the [failing build](http://slicer.cdash.org/viewConfigure.php?buildid=1608001) of SlicerCochlea for Slicer-Preview (aka nightly).

This also adds python 3 support. Updated code is expected to work with both Python2 and Python3. Therefore `master` branch here can be used for Slicer 4.10 and Slicer-Preview extension builds.

### CODE REVIEW

**Comment by jamesobutler** [comment]
@idhamari could you review this?

**Comment by idhamari** [comment]
Thanks for your comment, I already noticed that and I am updating all extension now to work both in python 2 and 3.

**Comment by jamesobutler** [comment]
Yes my commit https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/pull/13/commits/0b237d7654a4f7bd36556b2ef1b1d934220d76e2, should take care of the python 2 and python 3 compatibility.

**Comment by idhamari** [comment]
cool. thanks for your effort. A new update will come soon as I am changing some stuff.

**Pull request merged**
