### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @idhamari with @lassoan and @sjh26 in cc:

```
Subject: Help to merge https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/pull/43

Hi Al-Dhamari,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/pull/43

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by idhamari** [comment]
Thanks!

**Comment by jcfr** [comment]
@idhamari Thanks for taking the time to follow-up :pray: :rocket:

**Pull request merged**
